### ISSUE TITLE
Error in UseMethod("group_by_") :    no applicable method for 'group_by_' applied to an object of class "c('double', 'numeric')"

### ISSUE THREAD

**Issue by FemeniasM** [ammonthompson/zigzag#6]
Dear Ammon,
I followed the steps as detailed in the tutorial https://ammonthompson.github.io/zigzag/, however, I get an error when using the zigzag$new function. I tried with my own dataset and with the test dataset that is in quick_start_guide obtaining the same result:

**Error in UseMethod("group_by_") :    no applicable method for 'group_by_' applied to an object of class "c('double', 'numeric')"**

I would greatly appreciate if you can help me solve it,
best regards,

**Comment by ammonthompson** [comment]
Thank you for sending this. I suspect it is a conflict between matrixStats or coda and another package you have loaded earlier in your search path. I pushed a commit that should fix that problem. After you've reinstalled the package let me know if it worked. Thanks!

**Comment by FemeniasM** [comment]
I reinstalled the _coda_ and _matrixStats_ packages and it is working now. Thank you very much!

**Comment by ammonthompson** [comment]
Great! FYI, you only needed to reinstall zigzag. Best of luck.

**Comment by ammonthompson** [comment]
resolved issue.
