### ISSUE TITLE
error MCMC plots

### ISSUE THREAD

**Issue by SFonsecaCosta** [ammonthompson/zigzag#7]
Hi @ammonthompson 

I'm having this error (below) in one of my runs, you already saw this error in the plotting after MCMC run? if yes, you have some suggestion?

`Analyzing MCMC files. Writing to files located in:  mcmc_report ...
Error in .self$makeMCMCplots(model_log[, alpha_r_idx], paste0(mcmc_report_prefix,  : 
  too many parameters for plotting`

The probabilities are written as well as model parameters and other files. On the other side, the report lack the warnings and the .ess files.

Thanks a lot 

Sara

**Comment by ammonthompson** [comment]
Hi yes, this will be a simple simple fix. I forgot about an arbitrary limit I had put on the plotting. I'll be pushing a fix soon.

**Comment by ammonthompson** [comment]
Ok, I pushed an update. Let me know if you still have issues.
